//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.TcpTool {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.TcpTool.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 TCP Tool 的本地化字符串。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All clients 的本地化字符串。
        /// </summary>
        internal static string AllClients {
            get {
                return ResourceManager.GetString("AllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client log 的本地化字符串。
        /// </summary>
        internal static string ClientLogTitle {
            get {
                return ResourceManager.GetString("ClientLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string ClientSenderName {
            get {
                return ResourceManager.GetString("ClientSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string ClientTab {
            get {
                return ResourceManager.GetString("ClientTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected clients 的本地化字符串。
        /// </summary>
        internal static string ConnectedClientsTitle {
            get {
                return ResourceManager.GetString("ConnectedClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection failed 的本地化字符串。
        /// </summary>
        internal static string ConnectErrorTitle {
            get {
                return ResourceManager.GetString("ConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting... 的本地化字符串。
        /// </summary>
        internal static string ConnectingStatus {
            get {
                return ResourceManager.GetString("ConnectingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP client and server tool. 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string DisconnectButton {
            get {
                return ResourceManager.GetString("DisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEX 的本地化字符串。
        /// </summary>
        internal static string FormatHex {
            get {
                return ResourceManager.GetString("FormatHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string FormatText {
            get {
                return ResourceManager.GetString("FormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string FormatTitle {
            get {
                return ResourceManager.GetString("FormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network tools 的本地化字符串。
        /// </summary>
        internal static string GroupAccessibleName {
            get {
                return ResourceManager.GetString("GroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        internal static string GroupDisplayTitle {
            get {
                return ResourceManager.GetString("GroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEX to send 的本地化字符串。
        /// </summary>
        internal static string HexToSendTitle {
            get {
                return ResourceManager.GetString("HexToSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        internal static string HostTitle {
            get {
                return ResourceManager.GetString("HostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 的本地化字符串。
        /// </summary>
        internal static string IpTitle {
            get {
                return ResourceManager.GetString("IpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP Tool 的本地化字符串。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        internal static string MessagesTitle {
            get {
                return ResourceManager.GetString("MessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least one client 的本地化字符串。
        /// </summary>
        internal static string NoClientSelected {
            get {
                return ResourceManager.GetString("NoClientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string PortTitle {
            get {
                return ResourceManager.GetString("PortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server log 的本地化字符串。
        /// </summary>
        internal static string ServerLogTitle {
            get {
                return ResourceManager.GetString("ServerLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string ServerSenderName {
            get {
                return ResourceManager.GetString("ServerSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string ServerTab {
            get {
                return ResourceManager.GetString("ServerTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP 的本地化字符串。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show log 的本地化字符串。
        /// </summary>
        internal static string ShowLogToggle {
            get {
                return ResourceManager.GetString("ShowLogToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen failed 的本地化字符串。
        /// </summary>
        internal static string StartErrorTitle {
            get {
                return ResourceManager.GetString("StartErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message to send 的本地化字符串。
        /// </summary>
        internal static string TextToSendTitle {
            get {
                return ResourceManager.GetString("TextToSendTitle", resourceCulture);
            }
        }
    }
}
